CREATE DATABASE IF NOT EXISTS QuanLyNhaSach;
USE QuanLyNhaSach;

CREATE TABLE IF NOT EXISTS SACH (
    MaSach VARCHAR(50) PRIMARY KEY,
    TenSach VARCHAR(255) NOT NULL,
    TheLoai VARCHAR(255),
    TacGia VARCHAR(255),
    SoLuongTon INT DEFAULT 0,
    DonGia DECIMAL(15,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS THAMSO (
    SoLuongNhapItNhat INT DEFAULT 1,
    SoLuongTonToiDaTruocNhap INT DEFAULT 100
);

INSERT INTO THAMSO (SoLuongNhapItNhat, SoLuongTonToiDaTruocNhap)
VALUES (10, 100)
ON DUPLICATE KEY UPDATE SoLuongNhapItNhat = VALUES(SoLuongNhapItNhat), SoLuongTonToiDaTruocNhap = VALUES(SoLuongTonToiDaTruocNhap);

CREATE TABLE IF NOT EXISTS PHIEUNHAP (
    MaPhieuNhap INT AUTO_INCREMENT PRIMARY KEY,
    NgayNhap DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CHITIETPHIEUNHAP (
    MaPhieuNhap INT,
    MaSach VARCHAR(50),
    SoLuongNhap INT,
    DonGiaNhap DECIMAL(15,2),
    PRIMARY KEY (MaPhieuNhap, MaSach),
    FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAP(MaPhieuNhap),
    FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);

CREATE TABLE IF NOT EXISTS CHITIETPHIEUHOADON (
    MaPhieuHoaDon INT,
    MaSach VARCHAR(50),
    SoLuong INT,
    PRIMARY KEY (MaPhieuHoaDon, MaSach),
    FOREIGN KEY (MaSach) REFERENCES SACH(MaSach)
);
